import type { Metadata } from 'next'
import { Bebas_Neue, Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'
import Head from 'next/head'
import Script from 'next/script'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Konda Neon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Script type="text/javascript" src="https://unpkg.com/threejs-toys@0.0.8/build/threejs-toys.module.cdn.min.js" /> */}
      <body className={bebasNeue.className}>
        <div className='fixed z-20 top-0 w-full'>  
          <Header />
        </div>
        { children }
        <div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
